version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/nospy/Téléchargements/streaming:/mnt/media
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M