version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/nospy/Téléchargements/streaming:/mnt/media
    ports:
      - "8080:8080"